mobs:
  # - type: mob_type - https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
  #   baby: true/false - if mob have to be in baby form (by default all mobs that have baby form require it) (works only for mobs that have baby form)
  #   weak: true/false - if mob have to be under effect of potion of weakness
  #   maxHealth: 4 - max health mob can have to be caught
  #   maxSize: 1 - max size mob can be to be caught (works only for slime and magma_cube)
  - type: BAT
  - type: CHICKEN
  - type: PIG
  - type: COW
  - type: MUSHROOM_COW
  - type: SHEEP
  - type: HORSE
  - type: MULE
  - type: DONKEY
  - type: OCELOT
  - type: WOLF
  - type: VILLAGER

  - type: SLIME
    maxSize: 1
  - type: MAGMA_CUBE
    maxSize: 1

  - type: ZOMBIE
    weak: true
    maxHealth: 4
  - type: PIG_ZOMBIE
    weak: true
    maxHealth: 4
  - type: SILVERFISH
    weak: true
  - type: ENDERMITE
