emptyEgg:
  item: egg
  name: Empty Egg
  lore: []

  ## to disable
  #  > recipe: false
  ## shapeless
  #  > recipe:
  #  >   ingredients:
  #  >     - <item_name>
  #  >     ...
  ## shaped
  #  > recipe:
  #  >   shape:
  #  >     - " A "
  #  >     - "RR "
  #  >     - "ARR "
  #  >   ingredients:
  #  >     A: <item_name>
  #  >     R: <item_name>
  recipe:
    shape:
      - " I "
      - "IDI"
      - " I "
    ingredients:
      I: iron_ingot
      D: diamond

# Mobs that can be caught using empty egg and additional conditions that have to be met to catch specific mob.
mobs:
  # - type: mob_type - https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
  #   conditions:
  #     condition_name: <condition_value>
  #     ...
  - type: BAT
  - type: CHICKEN
    conditions:
      age: baby
  - type: PIG
    conditions:
      age: baby
  - type: COW
    conditions:
      age: baby
  - type: MUSHROOM_COW
    conditions:
      age: baby
  - type: SHEEP
    conditions:
      age: baby
  - type: HORSE
    conditions:
      age: baby
  - type: MULE
    conditions:
      age: baby
  - type: DONKEY
    conditions:
      age: baby
  - type: OCELOT
    conditions:
      age: baby
  - type: WOLF
    conditions:
      age: baby
  - type: VILLAGER
    conditions:
      age: baby

  - type: SLIME
    conditions:
      maxSize: 1
  - type: MAGMA_CUBE
    conditions:
      maxSize: 1

  - type: ZOMBIE
    conditions:
      weak: true
    maxHealth: 4
  - type: PIG_ZOMBIE
    conditions:
      weak: true
      maxHealth: 4
  - type: SILVERFISH
    conditions:
      weak: true
  - type: ENDERMITE

# Sounds played on successful catch and when mob can't be caught.
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
# Set to 'false' to disable.
sounds:
  success: ENTITY_CHICKEN_EGG
  failure: ENTITY_VILLAGER_NO
